apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubechecks
  namespace: kubechecks
spec:
  parentRefs:
    - name: external
      namespace: gateway
  hostnames:
    - "kubechecks.dev.masonfox.me"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kubechecks
          port: 8080
